services:
  vllm:
    container_name: vllm
    image: vllm/vllm-openai:latest
    gpus: all
    environment:
      VLLM_USE_V2_MODEL_RUNNER: "0"
    ports:
      - "8000:8000"
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    command:
      - --model
      - Qwen/Qwen2.5-0.5B-Instruct
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --gpu-memory-utilization
      - "0.7"
      - --max-model-len
      - "8192"
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      VLLM_BASE_URL: http://vllm:8000/v1
      VLLM_MODEL: Qwen/Qwen2.5-0.5B-Instruct

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
    - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    - prometheus-data:/prometheus
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
    - grafana-data:/var/lib/grafana
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
    - prometheus
    - loki
    
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command:
    - "-config.file=/etc/loki/local-config.yaml"
    
  alloy:
    image: grafana/alloy:latest
    volumes:
    - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
    - run
    - /etc/alloy/config.alloy
    depends_on:
    - loki
  
  cadvisor:
    image: ghcr.io/google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - "8081:8080"


volumes:
  huggingface-cache:
  prometheus-data:
  grafana-data: